import type { Metadata } from "next";
import PolicyPage, { type PolicySection } from "@/components/legal/PolicyPage";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How BrainADZ Live handles information shared through website enquiries, service discussions and product requests.",
  alternates: { canonical: "/privacy-policy" },
};

const sections: PolicySection[] = [
  { id: "scope", title: "About this policy", paragraphs: ["This policy describes how BrainADZ Live handles personal information shared through this website and related enquiries about our software development, business platforms, cloud consulting and digital signage products. Where we process information within a customer platform or project, the applicable project agreement and data processing arrangements also apply."] },
  { id: "information", title: "Information we receive", paragraphs: ["When you contact us, request a demo, ask for a quotation or discuss a project, we receive the information you choose to provide. Please share only information relevant to your request and avoid sending passwords, payment card details or sensitive customer records through an enquiry form."], bullets: ["Your name, email address, telephone number and company details.", "The service or product you are interested in, your message and project requirements.", "The page from which an enquiry is submitted and related submission details.", "Information you provide in follow-up emails, support requests or recruitment enquiries.", "Technical information that hosting and delivery systems may process, such as IP addresses, browser details and server logs."] },
  { id: "use", title: "How information is used", paragraphs: ["We use enquiry information to respond to your request, understand your requirements, prepare proposals, arrange demonstrations and communicate about agreed services or products. Information may also be needed to provide support, maintain business records, protect website systems and meet applicable legal obligations.", "Submitting an enquiry enables us to contact you about that enquiry. It does not, by itself, constitute permission for unrelated marketing communications."] },
  { id: "sharing", title: "Service providers and disclosure", paragraphs: ["Website hosting and email delivery providers process information as part of delivering website enquiries and communications. Information may be shared with personnel or delivery partners where needed to respond to your request or carry out an agreed project. Project-specific sharing should be addressed in the relevant agreement.", "Information may also be disclosed where required by law or a valid legal request. Links to external websites and social platforms are governed by those providers' own privacy policies."] },
  { id: "cookies", title: "Cookies and external services", paragraphs: ["Our hosting infrastructure and any external services you access may use cookies or similar technologies. You can control cookies through your browser settings, although blocking them may affect features provided by those services.", "This website's enquiry forms collect the details you enter. This policy does not treat visiting the website as consent to optional advertising or analytics tracking."] },
  { id: "retention", title: "Retention and security", paragraphs: ["Enquiries are delivered through email, so copies may remain in business mailboxes and associated provider systems. Retention depends on the purpose of the communication, ongoing project or support needs, and applicable recordkeeping requirements.", "Security measures must be appropriate to the information and systems involved. No internet transmission or storage system can be guaranteed completely secure; please avoid sharing confidential credentials through website forms."] },
  { id: "choices", title: "Your choices and requests", paragraphs: ["You can contact info@brainadzlive.com to ask about information you have shared, request a correction or deletion, withdraw permission where processing relies on your consent, or raise a privacy concern. Please include enough detail to identify the relevant enquiry without sending unnecessary sensitive information.", "Requests may require identity verification and are handled subject to applicable law and legitimate recordkeeping requirements. You may also ask us to stop optional promotional communications."] },
  { id: "children", title: "Children's information", paragraphs: ["The website is intended for business enquiries and is not directed at children. Please do not submit a child's personal information through our forms. If you believe such information has been submitted, contact us so the matter can be reviewed."] },
  { id: "updates", title: "Policy updates and contact", paragraphs: ["We may update this policy when website features, services or information handling practices change. The date at the top identifies the latest update. For privacy questions or concerns, email info@brainadzlive.com or use our Contact Us page."] },
];

export default function PrivacyPolicy() {
  return <PolicyPage title="Privacy Policy" heroImage="/hero/cloud-consulting.webp" description="How we handle the information you share while exploring our services, requesting a product or working with our team." sections={sections} />;
}
